server:
  port: "8080"
  read_timeout: 30
  write_timeout: 30

# Feature flags for V2 services - ROLLBACK: Disable V2 services
features:
  use_gonum_indicators: false      # TechnicalIndicatorServiceV2
  use_sequence_analyzer_v2: false  # SequenceAnalyzerV2  
  use_dataframe_aggregation: false # CandleAggregationServiceV2
  enable_indicator_caching: false  # Indicator caching system
  cache_ttl_minutes: 15           # Cache TTL in minutes
  
  # V2 Service Migration Flags - ROLLBACK: All disabled
  technical_indicators_v2: false  # Disable TechnicalIndicatorServiceV2
  candle_aggregation_v2: false    # Disable CandleAggregationServiceV2
  sequence_analyzer_v2: false     # Disable SequenceAnalyzerV2

# Analytics configuration for V2 services
analytics:
  sequence_analysis:
    min_sequence_length: 2
    max_gap_length: 5
    enable_pattern_detection: true
  
  indicator_cache:
    max_memory_mb: 100
    processing_pool_size: 4
    enable_persistence: false
    
  aggregation_engine:
    cache_size_mb: 256
    max_memory_usage_mb: 512
    worker_pool_size: 4
    timeout_duration_seconds: 30
    enable_caching: true
    
  # V2 Analytics Engine Configuration
  worker_pool_size: 4              # Number of worker goroutines
  max_concurrent_jobs: 8           # Maximum concurrent analytics jobs
  cache_size: 1000                 # Cache size for analytics results
  enable_optimizations: true       # Enable GoNum optimizations
  metrics_enabled: true            # Enable metrics collection

# Performance tuning configuration
performance:
  gonum_optimization:
    enable_parallel_processing: true
    batch_size: 1000
    max_concurrent_calculations: 8
  
  cache_strategy:
    policy: "lru"
    eviction_interval: "5m"
    compression: true
    
  dataframe_processing:
    enable_vectorization: true
    chunk_size: 5000
    parallel_aggregation: true
    memory_threshold_mb: 1024

dhan:
  base_url: "https://api.dhan.co"
  access_token: "xyz"
  client_id: "abc"

upstox:
  client_id: "abc"
  client_secret: "xyz" # API secret from Upstox Developer Console
  redirect_uri: "https://631b-114-142-166-214.ngrok-free.app/api/v1/upstox/callback" # Must match the URI registered in Upstox Developer Console
  base_path: "https://api.upstox.com"     # Upstox API base path

historical_data:
  maxConcurrentRequests: 5
  defaultInterval: "1minute"
  defaultDaysToFetch: 50
  defaultUserID: "default_user"
  retentionPeriodDays: 900
  batchSize: 1000
  enableAutoCleanup: false
  cleanupInterval: 99h

database:
  masterDatasource:
    user: setbull_trader
    password: setbull_trader
    host: 127.0.0.1:3306
    name: setbull_trader
  slaveDatasource:
    user: setbull_trader
    password: setbull_trader
    host: 127.0.0.1:3306
    name: setbull_trader
  maxIdleConnections: 5
  maxOpenConnections: 5
  maxConnectionLifetime: 50s
  maxConnectionIdletime: 50s
  disableTLS: true
  debug: true
cache:
  freecache:
    # In bytes, where 1024 * 1024 represents a single Megabyte. 256000000 = 256mb
    size: 256000000
    ttl: 1m
    disable: true
  redis:
    host: 127.0.01
    port: 6379
    database: 1
    idleConnectionTimeout: 20s
    connectTimeout: 20s
    readTimeout: 3s
    writeTimeout: 3s
    timeout: 3s
    tcpNoDelay: false
    poolSize: 128
    maxRetry: 3
    minIdle: 10
    ttl: 1m
    disable: false
  inmem:
    ttl: 1m
    cleanupttl: 1m