server:
  port: "8080"
  read_timeout: 30
  write_timeout: 30

# BBW Dashboard Configuration
bbw_dashboard:
  logging:
    level: "info"           # Log level (debug, info, warn, error, fatal)
    log_dir: "logs"         # Log directory
    max_size: 100           # Maximum log file size in MB
    max_backups: 30         # Number of backup files to keep
    max_age: 30             # Maximum age of log files in days
    compress: true          # Compress old log files
  alerting:
    default_threshold: 0.1      # Default alert threshold percentage
    default_lookback: 5         # Default contracting lookback period
    enable_audio_alerts: true   # Enable audio alerts
    alert_cooldown_minutes: 3   # Alert cooldown period
    max_alert_history: 100      # Maximum alert history entries
  processing:
    concurrent_workers: 10      # Number of concurrent processing workers
    processing_timeout: 30      # Processing timeout in seconds
    data_retention_days: 180    # Data retention period in days

dhan:
  base_url: "https://api.dhan.co"
  access_token: "xyz"
  client_id: "abc"

upstox:
  client_id: "abc"
  client_secret: "xyz" # API secret from Upstox Developer Console
  redirect_uri: "https://631b-114-142-166-214.ngrok-free.app/api/v1/upstox/callback" # Must match the URI registered in Upstox Developer Console
  base_path: "https://api.upstox.com"     # Upstox API base path

historical_data:
  maxConcurrentRequests: 5
  defaultInterval: "1minute"
  defaultDaysToFetch: 50
  defaultUserID: "default_user"
  retentionPeriodDays: 900
  batchSize: 1000
  enableAutoCleanup: false
  cleanupInterval: 99h

database:
  masterDatasource:
    user: setbull_trader
    password: setbull_trader
    host: 127.0.0.1:3306
    name: setbull_trader
  slaveDatasource:
    user: setbull_trader
    password: setbull_trader
    host: 127.0.0.1:3306
    name: setbull_trader
  maxIdleConnections: 5
  maxOpenConnections: 5
  maxConnectionLifetime: 50s
  maxConnectionIdletime: 50s
  disableTLS: true
  debug: true
cache:
  freecache:
    # In bytes, where 1024 * 1024 represents a single Megabyte. 256000000 = 256mb
    size: 256000000
    ttl: 1m
    disable: true
  redis:
    host: 127.0.01
    port: 6379
    database: 1
    idleConnectionTimeout: 20s
    connectTimeout: 20s
    readTimeout: 3s
    writeTimeout: 3s
    timeout: 3s
    tcpNoDelay: false
    poolSize: 128
    maxRetry: 3
    minIdle: 10
    ttl: 1m
    disable: false
  inmem:
    ttl: 1m
    cleanupttl: 1m