package strategies

import (
	"time"
)

// EntrySignal represents a trading signal generated by the strategy
type EntrySignal struct {
	Type      string                 `json:"type"`
	Direction string                 `json:"direction"`
	Price     float64                `json:"price"`
	Timestamp time.Time              `json:"timestamp"`
	Metadata  map[string]interface{} `json:"metadata"`
}
