/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for Cancel order request
type CancelOrderData struct {
	// Reference order ID
	OrderId string `json:"order_id,omitempty"`
}
