/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GttPlaceOrderRequest struct {
	// Type of GTT order. It can be one of the following: SINGLE refers to a single-leg GTT order MULTIPLE refers to a multi-leg GTT order
	Type_ string `json:"type"`
	// Quantity with which the order is to be placed
	Quantity int32 `json:"quantity"`
	// Signifies if the order was either Intraday, Delivery, CO or OCO
	Product string `json:"product"`
	// List of rules defining the conditions for each leg in the GTT order
	Rules []GttRule `json:"rules"`
	// Key of the instrument
	InstrumentToken string `json:"instrument_token"`
	// Indicates whether its a buy or sell order
	TransactionType string `json:"transaction_type"`
}
