/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for brokerage
type ProfitAndLossChargesWrapperData struct {
	ChargesBreakdown *ProfitAndLossChargesData `json:"charges_breakdown,omitempty"`
}
