/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for brokerage
type TradeWiseMetaData struct {
	// Total count of trades in the trade wise P and L report
	TradesCount int32 `json:"trades_count,omitempty"`
	// Maximum number of trades in a page of the trade wise P and L report API
	PageSizeLimit int32 `json:"page_size_limit,omitempty"`
}
