/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Meta data for trade wise data details
type ProfitAndLossMetaData struct {
	// pageNumber for pagination
	PageNumber int32 `json:"page_number,omitempty"`
	// Page size
	PageSize int32 `json:"page_size,omitempty"`
}
