/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CancelOrderV3Response struct {
	Status string `json:"status,omitempty"`
	Data *CancelOrderData `json:"data,omitempty"`
	Metadata *OrderMetadata `json:"metadata,omitempty"`
}
