/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketQuoteSymbolLtp struct {
	// The last traded price of symbol
	LastPrice float64 `json:"last_price,omitempty"`
	InstrumentToken string `json:"instrument_token,omitempty"`
}
