/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeHistoryResponseTradeData struct {
	Exchange string `json:"exchange,omitempty"`
	Segment string `json:"segment,omitempty"`
	OptionType string `json:"option_type,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Amount float32 `json:"amount,omitempty"`
	TradeId string `json:"trade_id,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	TransactionType string `json:"transaction_type,omitempty"`
	ScripName string `json:"scrip_name,omitempty"`
	StrikePrice string `json:"strike_price,omitempty"`
	Expiry string `json:"expiry,omitempty"`
	Price float32 `json:"price,omitempty"`
	Isin string `json:"isin,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	InstrumentToken string `json:"instrument_token,omitempty"`
}
