/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Other charges levied
type ProfitAndLossOtherChargesTaxes struct {
	// transaction charges
	Transaction float32 `json:"transaction,omitempty"`
	// clearing charges
	Clearing float32 `json:"clearing,omitempty"`
	// IPF charges
	Ipft float32 `json:"ipft,omitempty"`
	// others charges
	Others float32 `json:"others,omitempty"`
	// SEBI turnover
	SebiTurnover float32 `json:"sebi_turnover,omitempty"`
	// demat transaction charges
	DematTransaction float32 `json:"demat_transaction,omitempty"`
}
