/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IndieUserTokenRequest struct {
	// OAuth API key that is a public identifier for app
	ClientId string `json:"client_id,omitempty"`
	// OAuth client secret that is a private secret known only to app and authorization server
	ClientSecret string `json:"client_secret,omitempty"`
	// To enable/disable otp auth flow
	OtpVerificationDisabled bool `json:"otp_verification_disabled,omitempty"`
}
