/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// List of rules defining the conditions for each leg in the GTT order
type GttRule struct {
	// Defines the strategy for the GTT order leg: ENTRY - First leg order STOPLOSS - Stop-loss order TARGET - Target order
	Strategy string `json:"strategy"`
	// Trigger type for each leg of the order
	TriggerType string `json:"trigger_type"`
	// Trigger price for the GTT order leg
	TriggerPrice float64 `json:"trigger_price"`
}
