/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketQuoteOhlc struct {
	Ohlc *Ohlc `json:"ohlc,omitempty"`
	// The last traded price of symbol
	LastPrice float32 `json:"last_price,omitempty"`
	InstrumentToken string `json:"instrument_token,omitempty"`
}
