/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OAuthClientExceptionCauseStackTrace struct {
	ClassLoaderName string `json:"classLoaderName,omitempty"`
	ModuleName string `json:"moduleName,omitempty"`
	ModuleVersion string `json:"moduleVersion,omitempty"`
	MethodName string `json:"methodName,omitempty"`
	FileName string `json:"fileName,omitempty"`
	LineNumber int32 `json:"lineNumber,omitempty"`
	ClassName string `json:"className,omitempty"`
	NativeMethod bool `json:"nativeMethod,omitempty"`
}
