/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for margin
type MarginData struct {
	// Response data for instrument margin details
	Margins []Margin `json:"margins,omitempty"`
	// Total margin required to execute the orders
	RequiredMargin float64 `json:"required_margin,omitempty"`
	// Total margin after margin benefit
	FinalMargin float64 `json:"final_margin,omitempty"`
}
