/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Ohlc struct {
	// The open price of the trading session
	Open float64 `json:"open,omitempty"`
	// The high price of the trading session
	High float64 `json:"high,omitempty"`
	// The low price of the trading session
	Low float64 `json:"low,omitempty"`
	// The close price of the symbol from the previous session of trading
	Close float64 `json:"close,omitempty"`
}
