/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Execution summary for cancel or exit order request
type BatchExecutionSummary struct {
	// The total number of order lines present in the payload.
	Total int32 `json:"total,omitempty"`
	// The number of order lines that were successfully placed without any errors.
	Success int32 `json:"success,omitempty"`
	// The number of order lines that encountered errors during processing, despite their payloads being valid.
	Error_ int32 `json:"error,omitempty"`
}
