/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OAuthClientExceptionCauseSuppressed struct {
	StackTrace []OAuthClientExceptionCauseStackTrace `json:"stackTrace,omitempty"`
	Message string `json:"message,omitempty"`
	LocalizedMessage string `json:"localizedMessage,omitempty"`
}
