/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Rule struct {
	Strategy string `json:"strategy,omitempty"`
	Status string `json:"status,omitempty"`
	Message string `json:"message,omitempty"`
	TriggerType string `json:"trigger_type,omitempty"`
	TriggerPrice float64 `json:"trigger_price,omitempty"`
	TransactionType string `json:"transaction_type,omitempty"`
	OrderId string `json:"order_id,omitempty"`
}
