/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for cancel or exit order request
type CancelOrExitMultiOrderData struct {
	// Reference order IDs
	OrderIds []string `json:"order_ids,omitempty"`
}
