/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Taxes levied on order
type ProfitAndLossChargesTaxes struct {
	// GST charges
	Gst float32 `json:"gst,omitempty"`
	// STT charges
	Stt float32 `json:"stt,omitempty"`
	// Stamp duty charges
	StampDuty float32 `json:"stamp_duty,omitempty"`
}
