/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for GTT order request
type GttOrderData struct {
	// Order ID for the placed GTT order
	GttOrderIds []string `json:"gtt_order_ids,omitempty"`
}
