/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GttCancelOrderRequest struct {
	// Unique identifier of the GTT order to be cancelled
	GttOrderId string `json:"gtt_order_id"`
}
