/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DepthMap struct {
	// Bids
	Buy []Depth `json:"buy,omitempty"`
	// Asks
	Sell []Depth `json:"sell,omitempty"`
}
