/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeHistoryResponsePageData struct {
	PageNumber int32 `json:"page_number,omitempty"`
	PageSize int32 `json:"page_size,omitempty"`
	TotalRecords int32 `json:"total_records,omitempty"`
	TotalPages int32 `json:"total_pages,omitempty"`
}
