/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response data for order details
type GttOrderDetails struct {
	Type_ string `json:"type,omitempty"`
	Exchange string `json:"exchange,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Product string `json:"product,omitempty"`
	Rules []Rule `json:"rules,omitempty"`
	TradingSymbol string `json:"trading_symbol,omitempty"`
	InstrumentToken string `json:"instrument_token,omitempty"`
	GttOrderId string `json:"gtt_order_id,omitempty"`
	ExpiresAt int64 `json:"expires_at,omitempty"`
	CreatedAt int64 `json:"created_at,omitempty"`
}
