/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DpPlan struct {
	// Name
	Name string `json:"name,omitempty"`
	// Minimum expense charges
	MinExpense float32 `json:"min_expense,omitempty"`
}
