/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetTradeWiseProfitAndLossDataResponse struct {
	Status string `json:"status,omitempty"`
	// Response data for trade wise data details
	Data []TradeWiseProfitAndLossData `json:"data,omitempty"`
	Metadata *ProfitAndLossMetaDataWrapper `json:"metadata,omitempty"`
}
