ALTER TABLE stock_candle_data
  ADD COLUMN ema_5 DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN ema_9 DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN ema_50 DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN atr DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN rsi DECIMAL(18,4) DEFAULT NULL;