ALTER TABLE stock_candle_data
  ADD COLUMN ma_9 DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN bb_upper DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN bb_middle DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN bb_lower DECIMAL(18,4) DEFAULT NULL,
  ADD COLUMN vwap DECIMAL(18,4) DEFAULT NULL;